version: "3"

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=creative
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pop123abd
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=creative
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pop123abd
      - POSTGRES_HOST=db